routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', function(){
    return view('auth.login');
});



Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('unit-organisasi', 'UnitOrganisasiController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('golongan', 'GolonganController');
    Route::resource('user', 'UserController');
    Route::resource('mutasi', 'MutasiController');
    Route::get('pensiun', 'PensiunController@index')->name('pensiun.index');
    Route::get('pensiun/create', 'PensiunController@create')->name('pensiun.create');
    Route::post('pensiun/store', 'PensiunController@store')->name('pensiun.store');
    Route::get('pensiun/{id}', 'PensiunController@edit')->name('pensiun.edit');
    Route::put('pensiun/{id}', 'PensiunController@update')->name('pensiun.update');
    Route::delete('pensiun/{id}', 'PensiunController@destroy')->name('pensiun.destroy');
    Route::get('info-unit-organisasi', 'PegawaiController@eksePegawai')->name('ekse-pegawai');

    Route::get('print-pegawai-organisasi/{id}', 'PrintController@printPegawaiOrganisasi')->name('print.pegawaiOrganisasi');
    Route::get('print-pegawai/{id}', 'PrintController@printPegawai')->name('print.pegawai');
    Route::get('print-mutasi/{id}', 'PrintController@printMutasi')->name('print.mutasi');
    Route::get('print-surat-penugasan/{id}', 'PrintController@printSuratPenugasan')->name('print.suratPenugasan');
});

app/Golongan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Golongan extends Model
{
    protected $table = 'golongan';
    protected $fillable = [
        'pegawai_id',
        'golongan',
        'no_sk',
        'tanggal_sk',
        'tmt_golongan',

    ];

    public static function getDefaultValues()
    {
        return (object) [
            'pegawai_id' => '',
            'golongan' => '',
            'no_sk' => '',
            'tanggal_sk' => '',
            'tmt_golongan' => '',
        ];
    }

    public static function getGolonganList()
    {
        return [
            'I A', 'I B', 'I C',
            'II A', 'II B', 'II C',
            'III A', 'III B', 'III C',
            'IV A', 'IV B', 'IV C'
        ];
    }

    public function pegawai()
    {
        return $this->belongsTo('App\Pegawai');
    }
}

app/Http/Controllers/GolonganController.php
<?php

namespace App\Http\Controllers;

use App\Golongan;
use App\Pegawai;
use Illuminate\Http\Request;

class GolonganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('read-only', ['except' => ['index']]);
    }

    public function index()
    {
        $data['golongan'] = Golongan::all();
        return view("golongan.index", $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['golongan'] = Golongan::getDefaultValues();
        $data['pegawai'] = Pegawai::orderBy('nama')->get();
        return view("golongan.form", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'pegawai_id' => 'required',
            'golongan' => 'required',
            'no_sk' => 'required',
            'tanggal_sk' => 'required',
            'tmt_golongan' => 'required',
        ]);

        Golongan::create($request->toArray());
        return redirect()->route('golongan.index')->with('success', 'Berhasil menambah golongan pegawai');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['pegawai'] = Pegawai::orderBy('nama')->get();
        $data['golongan'] = Golongan::find($id);
        return view("golongan.form", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'pegawai_id' => 'required',
            'golongan' => 'required',
            'no_sk' => 'required',
            'tanggal_sk' => 'required',
            'tmt_golongan' => 'required',
        ]);

        Golongan::find($id)->update($request->toArray());
        return redirect()->route('golongan.index')->with('success', 'Berhasil mengubah golongan pegawai');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Golongan::find($id)->delete();
        return redirect()->route('golongan.index')->with('success', 'Berhasil menghapus golongan pegawai');
    }
}

resources/views/golongan/form.blade.php
@extends('layouts.app')

@section('title', 'Golongan')



@section('content')
<div class="row ">
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Golongan</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($golongan->id)) ? route('golongan.store') : route('golongan.update', $golongan->id) }}" method="post">
                    @csrf
                    @isset($golongan->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Pegawai</label>
                        <select name="pegawai_id" id="" class="mySelect form-control">
                            <option value="">- Pilih Pegawai -</option>
                            @foreach($pegawai as $option)
                                <option value="{{ $option->id }}" {{ $option->id == old('pegawai_id', $golongan->pegawai_id) ? 'selected' : '' }}>{{ $option->nik . ' - ' . $option->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="">Golongan</label>
                                <select name="golongan" id="" class="mySelect form-control">
                                    <option value="">- Pilih Golongan -</option>
                                    @foreach(App\Golongan::getGolonganList() as $option)
                                        <option value="{{ $option }}" {{ $option == old('golongan', $golongan->golongan) ? 'selected' : '' }}>{{ $option }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label for="">No. SK</label>
                                <input type="text" name="no_sk" value="{{ old('no_sk', $golongan->no_sk) }}" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="">Tanggal SK</label>
                                <input type="text" name="tanggal_sk" value="{{ old('tanggal_sk', $golongan->tanggal_sk) }}" class="form-control datepicker2">
                            </div>
                            <div class="col-md-6">
                                <label for="">TMT Golongan</label>
                                <input type="text" name="tmt_golongan" value="{{ old('tmt_golongan', $golongan->tmt_golongan) }}" class="form-control datepicker2">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <input type="submit" class="btn btn-primary float-right mt-4" value="Simpan">
                            </div>
                        </div>
                    </div>


                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/golongan/index.blade.php
@extends('layouts.app')

@section('title', 'Golongan')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Golongan</h4>
            </div>
            <div class="card-body">
                @if(Auth::user()->level != 'Kepala Sub-bagian')

                    <a href="{{ route('golongan.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah</a>
                @endif
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>NIK</th>
                            <th>Nama</th>
                            <th>Golongan</th>
                            <th>No. SK</th>
                            <th>Tgl. SK</th>
                            <th>TMT. Gol</th>
                            <th>Jenis KP</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($golongan->count() != 0)
                            @foreach($golongan as $row)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $row->pegawai->nik }}</td>
                                    <td>{{ $row->pegawai->nama }}</td>
                                    <td>{{ $row->golongan }}</td>
                                    <td>{{ $row->no_sk }}</td>
                                    <td>{{ $row->tanggal_sk }}</td>
                                    <td>{{ $row->tmt_golongan }}</td>
                                    <td>{{ $row->jenis_kp }}</td>
                                    <td>
                                        @if(Auth::user()->level != 'Kepala Sub-bagian')
                                            <form action="{{ route('golongan.destroy', $row->id) }}" method="post">
                                                <ul class="d-flex action-button">
                                                    <li><a href="{{ route('golongan.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                                    @csrf
                                                    @method('delete')
                                                    <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                                </ul>
                                            </form>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="3">Belum ada data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection