routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', function(){
    return view('auth.login');
});



Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('unit-organisasi', 'UnitOrganisasiController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('golongan', 'GolonganController');
    Route::resource('user', 'UserController');
    Route::resource('mutasi', 'MutasiController');
    Route::get('pensiun', 'PensiunController@index')->name('pensiun.index');
    Route::get('pensiun/create', 'PensiunController@create')->name('pensiun.create');
    Route::post('pensiun/store', 'PensiunController@store')->name('pensiun.store');
    Route::get('pensiun/{id}', 'PensiunController@edit')->name('pensiun.edit');
    Route::put('pensiun/{id}', 'PensiunController@update')->name('pensiun.update');
    Route::delete('pensiun/{id}', 'PensiunController@destroy')->name('pensiun.destroy');
    Route::get('info-unit-organisasi', 'PegawaiController@eksePegawai')->name('ekse-pegawai');

    Route::get('print-pegawai-organisasi/{id}', 'PrintController@printPegawaiOrganisasi')->name('print.pegawaiOrganisasi');
    Route::get('print-pegawai/{id}', 'PrintController@printPegawai')->name('print.pegawai');
    Route::get('print-mutasi/{id}', 'PrintController@printMutasi')->name('print.mutasi');
    Route::get('print-surat-penugasan/{id}', 'PrintController@printSuratPenugasan')->name('print.suratPenugasan');
});

app/UnitOrganisasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UnitOrganisasi extends Model
{
    protected $table = 'unit_organisasi';
    protected $fillable = [
        'nama_unit_organisasi',
        'keterangan',
        'kapasitas',
    ];

    public static function getDefaultValues()
    {
        return (object) [
            'nama_unit_organisasi' => '',
            'keterangan' => '',
            'kapasitas' => '',
        ];
    }
}

app/Http/Controllers/UnitOrganisasiController.php
<?php

namespace App\Http\Controllers;

use App\JabatanPegawai;
use App\Pegawai;
use App\UnitOrganisasi;
use Illuminate\Http\Request;

class UnitOrganisasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('read-only', ['except' => ['index', 'show']]);
    }

    public function index()
    {
        $data['unit_organisasi'] = UnitOrganisasi::all();
        return view("unit_organisasi.index", $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['unit_organisasi'] = UnitOrganisasi::getDefaultValues();
        return view("unit_organisasi.form", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_unit_organisasi' => 'required'
        ]);

        UnitOrganisasi::create($request->toArray());
        return redirect()->route('unit-organisasi.index')->with('success', 'Berhasil menambah unit organisasi');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['unit_organisasi'] = UnitOrganisasi::findOrFail($id);
        $data['pegawai'] = JabatanPegawai::where("jabatan_sekarang", 'true')->where('unit_organisasi_id', $id)->get();
        return view('unit_organisasi.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['unit_organisasi'] = UnitOrganisasi::find($id);
        return view("unit_organisasi.form", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_unit_organisasi' => 'required'
        ]);

        UnitOrganisasi::find($id)->update($request->toArray());
        return redirect()->route('unit-organisasi.index')->with('success', 'Berhasil mengubah unit organisasi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $unit_org = UnitOrganisasi::find($id);

        $jabatan_peg = JabatanPegawai::where('unit_organisasi_id', $id)->get();

        if($jabatan_peg->count() == 0) {
            $unit_org->delete();
        } else {
            return redirect()->route('unit-organisasi.index')->with('error', 'Gagal menghapus unit organisasi karena record tersebut memiliki pegawai.');
        }

        return redirect()->route('unit-organisasi.index')->with('success', 'Berhasil menghapus unit organisasi');
    }
}

resources/views/unit_organisasi/form.blade.php
@extends('layouts.app')

@section('title', 'Unit Organisasi')



@section('content')
<div class="row ">  
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Bidang</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($unit_organisasi->id)) ? route('unit-organisasi.store') : route('unit-organisasi.update', $unit_organisasi->id) }}" method="post">
                    @csrf
                    @isset($unit_organisasi->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">       
                        <label>Nama</label>
                        <input type="text" placeholder="Nama Bidang/Unit" class="form-control" name="nama_unit_organisasi" value="{{ old('nama_unit_organisasi', $unit_organisasi->nama_unit_organisasi) }}">
                    </div>
                    <div class="form-group">
                        <label>Kapasitas</label>
                        <input type="number" placeholder="Kapasitas Pegawai" class="form-control" name="kapasitas" value="{{ old('kapasitas', $unit_organisasi->kapasitas) }}">
                    </div>
                    <div class="form-group">
                        <label>Keterangan</label>
                        <textarea name="keterangan" class="form-control" placeholder="Masukan Keterangan (opsional)">{{ old('keterangan', $unit_organisasi->keterangan) }}</textarea>
                    </div>    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>    
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/unit_organisasi/index.blade.php
@extends('layouts.app')

@section('title', 'Bidang/Unit')



@section('content')
<div class="row ">  
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Bidang/Unit</h4>
            </div>
            <div class="card-body">
                @if(Auth::user()->level != 'Kepala Sub-bagian')
                    <a href="{{ route('unit-organisasi.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah</a>
                @endif
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Bidang/Unit</th>
                            <th>Kapasitas</th>
                            <th>Keterangan</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($unit_organisasi->count() != 0)
                            @foreach($unit_organisasi as $row)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $row->nama_unit_organisasi }}</td> 
                                    <td>{{ $row->kapasitas }}</td>
                                    <td>{{ $row->keterangan }}</td>
                                    <td>
                                        
                                        <form action="{{ route('unit-organisasi.destroy', $row->id) }}" method="post">
                                            <ul class="d-flex action-button">                                        
                                                <li><a href="{{ route('unit-organisasi.show', $row->id) }}" class="text-primary" title="Lihat Pegawai"><i class="fa fa-user-tie"></i></a></li>                                                
                                                @if(Auth::user()->level != 'Kepala Sub-bagian')
                                                    <li><a href="{{ route('unit-organisasi.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                                    @csrf
                                                    @method('delete')
                                                    <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                                @endif
                                            </ul>
                                        </form>
                                        
                                    </td>
                                </tr>   
                            @endforeach
                        @else 
                            <tr>
                                <td colspan="3">Belum ada data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/unit_organisasi/show.blade.php
@extends('layouts.app')

@section('title', 'Pegawai Perbidang')



@section('content')
<div class="row ">  
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Pegawai Perbidang</h4>
            </div>
            <div class="card-body">
                <a href="{{ route('print.pegawaiOrganisasi', $unit_organisasi->id) }}" class="btn btn-primary mb-3" target="_blank">Print</a>
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>NIK</th>
                            <th>Nama</th>
                            <th>Unit Organisasi</th>
                            <th>Jabatan</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($pegawai->count() != 0)
                            @foreach($pegawai as $row)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $row->pegawai->nik }}</td> 
                                    <td>{{ $row->pegawai->nama }}</td>
                                    <td>{{ $unit_organisasi->nama_unit_organisasi }}</td>
                                    <td>{{ $row->jabatan->nama_jabatan }}</td>
                                </tr>   
                            @endforeach
                        @else 
                            <tr>
                                <td colspan="3">Belum ada data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection