routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', function(){
    return view('auth.login');
});



Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('unit-organisasi', 'UnitOrganisasiController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('golongan', 'GolonganController');
    Route::resource('user', 'UserController');
    Route::resource('mutasi', 'MutasiController');
    Route::get('pensiun', 'PensiunController@index')->name('pensiun.index');
    Route::get('pensiun/create', 'PensiunController@create')->name('pensiun.create');
    Route::post('pensiun/store', 'PensiunController@store')->name('pensiun.store');
    Route::get('pensiun/{id}', 'PensiunController@edit')->name('pensiun.edit');
    Route::put('pensiun/{id}', 'PensiunController@update')->name('pensiun.update');
    Route::delete('pensiun/{id}', 'PensiunController@destroy')->name('pensiun.destroy');
    Route::get('info-unit-organisasi', 'PegawaiController@eksePegawai')->name('ekse-pegawai');

    Route::get('print-pegawai-organisasi/{id}', 'PrintController@printPegawaiOrganisasi')->name('print.pegawaiOrganisasi');
    Route::get('print-pegawai/{id}', 'PrintController@printPegawai')->name('print.pegawai');
    Route::get('print-mutasi/{id}', 'PrintController@printMutasi')->name('print.mutasi');
    Route::get('print-surat-penugasan/{id}', 'PrintController@printSuratPenugasan')->name('print.suratPenugasan');
});

app/Http/Controllers/MutasiController.php
<?php

namespace App\Http\Controllers;

use App\Jabatan;
use App\JabatanPegawai;
use App\Pegawai;
use App\UnitOrganisasi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MutasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    
    public function index(Request $request)
    {
        $data['pegawai'] = Pegawai::orderBy('nama', 'asc')->get();
        $data['jabatan_pegawai'] = null;
        if(isset($request->pegawai_id)) {
            $data['pegawai_single'] = Pegawai::findOrFail($request->pegawai_id);
            $data['jabatan_pegawai'] = JabatanPegawai::where('pegawai_id', $request->pegawai_id)->orderBy('tmt_jabatan', 'desc')->get();
        }

        return view('mutasi.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->level == 'Kepala Sub-bagian') {
        
            $data['mutasi'] = JabatanPegawai::getDefaultValues();
            $data['pegawai'] = Pegawai::orderBy('nama', 'asc')->get();
            $data['unit_organisasi'] = UnitOrganisasi::orderBy('nama_unit_organisasi', 'asc')->where('nama_unit_organisasi', '!=', 'Pensiun')->get();
            $data['jabatan'] = Jabatan::orderBy('nama_jabatan', 'asc')->where('nama_jabatan', '!=', 'Pensiun')->get();
            return view('mutasi.form', $data);
        } else {
            return "Unauthorized";
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::user()->level == 'Kepala Sub-bagian') {
            $request->validate([
                'pegawai_id' => 'required',
                'unit_organisasi_id' => 'required',
                'jabatan_id' => 'required',
                'tmt_jabatan' => 'required',
                'tgl_sk' => 'required',
                'no_sk' => 'required',
                
            ]);

            JabatanPegawai::create($request->toArray());
            JabatanPegawai::updateJabatanSekarang($request->pegawai_id);
            return redirect('mutasi?pegawai_id='.$request->pegawai_id)->with('success', 'Berhasil menambahkan mutasi pegawai');
        } else {
            return "Unauthorized";
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->level == 'Kepala Sub-bagian') {
            $data['mutasi'] = JabatanPegawai::findOrFail($id);
            $data['pegawai'] = Pegawai::orderBy('nama', 'asc')->get();
            $data['unit_organisasi'] = UnitOrganisasi::orderBy('nama_unit_organisasi', 'asc')->get();
            $data['jabatan'] = Jabatan::orderBy('nama_jabatan', 'asc')->get();
            return view('mutasi.form', $data);
        } else {
            return "Unauthorized";
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::user()->level == 'Kepala Sub-bagian') {
            $request->validate([
                'pegawai_id' => 'required',
                'unit_organisasi_id' => 'required',
                'jabatan_id' => 'required',
                'tmt_jabatan' => 'required',
                'tgl_sk' => 'required',
                'no_sk' => 'required',
                
            ]);

            JabatanPegawai::find($id)->update($request->toArray());
            JabatanPegawai::updateJabatanSekarang($id);
            return redirect('mutasi?pegawai_id='.$request->pegawai_id)->with('success', 'Berhasil mengubah mutasi pegawai');
        } else {
            return "Unauthorized";
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->level == 'Kepala Sub-bagian') {
            JabatanPegawai::find($id)->delete();
            return redirect('mutasi?pegawai_id='.$_GET['pegawai_id'])->with('success', 'Berhasil menghapus mutasi pegawai');
        } else {
            return "Unauthorized";
        }

    }
}

resources/views/mutasi/form.blade.php
@extends('layouts.app')

@section('title', 'Form Mutasi')



@section('content')
<div class="row ">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Mutasi</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($mutasi->id)) ? route('mutasi.store') : route('mutasi.update', $mutasi->id) }}" method="post">
                    @csrf
                    @isset($mutasi->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label for="Pegawai">Pegawai</label>

                        <select name="" id="" class="mySelect form-control" disabled>
                            <option value="">- Pilih Pegawai -</option>
                            @foreach($pegawai as $option)
                                <option value="{{ $option->id }}" {{ $option->id == old('pegawai_id', $_GET['pegawai_id']) ? 'selected' : '' }}>{{ $option->nik . ' - ' . $option->nama }}</option>
                            @endforeach
                        </select>

                        <input type="hidden" name="pegawai_id" value="{{ old('pegawai_id', $_GET['pegawai_id']) }}">
                    </div>
                    <div class="form-group">
                        <label>Unit Organisasi</label>
                        <select name="unit_organisasi_id" id="" class="mySelect form-control">
                            <option value="">- Pilih Unit Organisasi -</option>
                            @foreach($unit_organisasi as $option)
                                <option value="{{ $option->id }}" {{ $option->id == old('unit_organisasi_id', $mutasi->unit_organisasi_id) ? 'selected' : '' }}>{{ $option->nama_unit_organisasi }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Jabatan</label>
                        <select name="jabatan_id" id="" class="mySelect form-control">
                            <option value="">- Pilih Jabatan -</option>
                            @foreach($jabatan as $option)
                                <option value="{{ $option->id }}" {{ $option->id == old('jabatan_id', $mutasi->jabatan_id) ? 'selected' : '' }}>{{ $option->nama_jabatan }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Eselon</label>
                        <select name="eselon" id="" class="mySelect form-control">
                            <option value="">- Pilih Eselon -</option>
                            @foreach(App\JabatanPegawai::eselonList() as $option)
                                <option value="{{ $option }}" {{ $option == old('eselon', $mutasi->eselon) ? 'selected' : '' }}>{{ $option }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>TMT Jabatan</label>
                        <input type="text" placeholder="TMT Jabatan" class="form-control datepicker2" name="tmt_jabatan" value="{{ old('tmt_jabatan', $mutasi->tmt_jabatan) }}">
                    </div>
                    <div class="form-group">
                        <label>Tanggal SK</label>
                        <input type="text" placeholder="Tanggal SK" class="form-control datepicker2" name="tgl_sk" value="{{ old('tgl_sk', $mutasi->tgl_sk) }}">
                    </div>
                    <div class="form-group">
                        <label>No. SK</label>
                        <input type="text" placeholder="No. SK" class="form-control" name="no_sk" value="{{ old('tgl_sk', $mutasi->no_sk) }}">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mutasi/index.blade.php
@extends('layouts.app')

@section('title', 'Mutasi')



@section('content')
<div class="row ">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Pegawai</h4>
            </div>
            <div class="card-body">
                <form action="" method="get">
                    <div class="form-group">
                        <label for="Pegawai">Pegawai</label>
                        <select name="pegawai_id" id="" class="mySelect form-control">
                            <option value="">- Pilih Pegawai -</option>
                            @foreach($pegawai as $option)
                                <option value="{{ $option->id }}" {{ $option->id == old('pegawai_id', $_GET['pegawai_id'] ?? '') ? 'selected' : '' }}>{{ $option->nik . ' - ' . $option->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Cari" class="btn btn-primary float-right">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@if(isset($pegawai_single))

<div class="row">
    <div class="col-md-12">
        @if(Auth::user()->level == 'Kepala Sub-bagian')
            @if($jabatan_pegawai->count() != 0)
                @if($jabatan_pegawai[0]->unitOrganisasi->nama_unit_organisasi != 'Pensiun')
                    <a href="{{ route('mutasi.create') }}?pegawai_id={{ $_GET['pegawai_id'] }}" class="btn btn-primary mb-3">Tambah Mutasi</a>
                @endif
            @else
                <a href="{{ route('mutasi.create') }}?pegawai_id={{ $_GET['pegawai_id'] }}" class="btn btn-primary mb-3">Tambah Mutasi</a>
            @endif
        @endif
        <a href="{{ route('print.mutasi', $_GET['pegawai_id']) }}" class="btn btn-outline-primary mb-3 ">Print Mutasi</a>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>Jabatan Sekarang</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama</th>
                            <th>Unit Organisasi</th>
                            <th>Jabatan</th>
                            <th>Eselon</th>
                            <th>TMT Jabatan</th>
                            <th>Tgl SK</th>
                            <th>No SK</th>
                            <th>Print</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($jabatan_pegawai->count() != 0)
                        <tr>
                            <td>1</td>
                            <td>{{ $jabatan_pegawai[0]->pegawai->nik . ' - ' . $jabatan_pegawai[0]->pegawai->nama }}</td>
                            <td>{{ $jabatan_pegawai[0]->unitOrganisasi->nama_unit_organisasi }}</td>
                            <td>{{ $jabatan_pegawai[0]->jabatan->nama_jabatan }}</td>
                            <td>{{ $jabatan_pegawai[0]->eselon }}</td>
                            <td>{{ $jabatan_pegawai[0]->tmt_jabatan }}</td>
                            <td>{{ $jabatan_pegawai[0]->tgl_sk }}</td>
                            <td>{{ $jabatan_pegawai[0]->no_sk }}</td>
                            <td>
                                @if($jabatan_pegawai[0]->unitOrganisasi->nama_unit_organisasi != 'Pensiun')
                                    <a href="{{ route('print.suratPenugasan', $jabatan_pegawai[0]->id) }}" target="_blank">Surat Penugasan</a>
                                @endif
                            </td>
                        </tr>
                        @else
                            <tr>
                                <td colspan="7">Belum ada data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>Riwayat Mutasi</h3>

                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama</th>
                            <th>Unit Organisasi</th>
                            <th>Jabatan</th>
                            <th>Eselon</th>
                            <th>TMT Jabatan</th>
                            <th>Tgl SK</th>
                            <th>No SK</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($jabatan_pegawai->count() >= 2)
                            @foreach($jabatan_pegawai as $key => $row)
                                @if($key == 0)
                                    @continue
                                @endif
                                <tr>
                                    <td>{{ $loop->iteration - 1 }}</td>
                                    <td>{{ $row->pegawai->nik . ' - ' . $row->pegawai->nama }}</td>
                                    <td>{{ $row->unitOrganisasi->nama_unit_organisasi }}</td>
                                    <td>{{ $row->jabatan->nama_jabatan }}</td>
                                    <td>{{ $row->eselon }}</td>
                                    <td>{{ $row->tmt_jabatan }}</td>
                                    <td>{{ $row->tgl_sk }}</td>
                                    <td>{{ $row->no_sk }}</td>
                                    <td>
                                        @if(Auth::user()->level == 'Kepala Sub-bagian')
                                            <form action="{{ route('mutasi.destroy', $row->id) }}?pegawai_id={{ $_GET['pegawai_id'] }}" method="post">
                                                <ul class="d-flex action-button">
                                                    <li><a href="{{ route('mutasi.edit', $row->id) }}?pegawai_id={{ $_GET['pegawai_id'] }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                                    @csrf
                                                    @method('delete')
                                                    <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                                </ul>
                                            </form>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="7">Belum ada data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endif



@endsection

@push('scripts')

<script>
    //$('.pegawai-sidebar').addClass('active');
</script>

@endpush