routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', function(){
    return view('auth.login');
});



Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('unit-organisasi', 'UnitOrganisasiController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('golongan', 'GolonganController');
    Route::resource('user', 'UserController');
    Route::resource('mutasi', 'MutasiController');
    Route::get('pensiun', 'PensiunController@index')->name('pensiun.index');
    Route::get('pensiun/create', 'PensiunController@create')->name('pensiun.create');
    Route::post('pensiun/store', 'PensiunController@store')->name('pensiun.store');
    Route::get('pensiun/{id}', 'PensiunController@edit')->name('pensiun.edit');
    Route::put('pensiun/{id}', 'PensiunController@update')->name('pensiun.update');
    Route::delete('pensiun/{id}', 'PensiunController@destroy')->name('pensiun.destroy');
    Route::get('info-unit-organisasi', 'PegawaiController@eksePegawai')->name('ekse-pegawai');

    Route::get('print-pegawai-organisasi/{id}', 'PrintController@printPegawaiOrganisasi')->name('print.pegawaiOrganisasi');
    Route::get('print-pegawai/{id}', 'PrintController@printPegawai')->name('print.pegawai');
    Route::get('print-mutasi/{id}', 'PrintController@printMutasi')->name('print.mutasi');
    Route::get('print-surat-penugasan/{id}', 'PrintController@printSuratPenugasan')->name('print.suratPenugasan');
});

app/Pegawai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    protected $table = 'pegawai';
    protected $fillable = [
        'nama',
        'gelar_depan',
        'gelar_belakang',
        'tempat_lahir',
        'tanggal_lahir',
        'jenis_kelamin', //'Laki - laki', 'Perempuan',
        'alamat',
        'no_telp',
        'email',
        'nik',
        'nip', //(unique)
        'tmt_pns',
        'tmt_cpns',
        'jenis_pegawai',
        'no_sk_kepala_dinas',
        'no_urut_umum',
        'sk_pns',
    ];

    public static function getDefaultValues()
    {
        return (object) [
            'nama' => '',
            'gelar_depan' => '',
            'gelar_belakang' => '',
            'tempat_lahir' => '',
            'tanggal_lahir' => '',
            'jenis_kelamin' => '', //'Laki - laki', 'Perempuan',
            'alamat' => '',
            'no_telp' => '',
            'email' => '',
            'nik' => '',
            'nip' => '', //(unique)
            'tmt_pns' => '',
            'tmt_cpns' => '',
            'jenis_pegawai' => '',
            'no_sk_kepala_dinas' => '',
            'no_urut_umum' => '',
            'sk_pns' => ''
        ];
    }


    public function namaGelar()
    {
        if($this->gelar_depan != null) {
            $gelar_1 = $this->gelar_depan . ' ';
        } else {
            $gelar_1 = '';
        }

        if($this->gelar_belakang != null) {
            $gelar_2 = $this->gelar_belakang . ' ';
        } else {
            $gelar_2 = '';
        }

        return $gelar_1.$this->nama. ' ' .$gelar_2;
    }
    public function jenisPegawai()
    {
        if($this->jenis_pegawai == 1) {
            return 'PNS';
        } else {
            return 'Non-PNS / Kontrak / Lainnya';
        }
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Golongan;
use App\JabatanPegawai;
use App\Pegawai;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('read-only', ['except' => ['index', 'eksePegawai']]);
    }

    public function index()
    {
        $data['pegawai'] = Pegawai::all();
        return view("pegawai.index", $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['pegawai'] = Pegawai::getDefaultValues();
        return view("pegawai.form", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'nama' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required', //'Laki - laki', 'Perempuan',
            'alamat' => 'required',
            'no_telp' => 'required',
            'email' => 'required',
            'nik' => 'required|unique:pegawai',
            'jenis_pegawai' => 'required',
        ]);

        if($request->jenis_pegawai == 2) {
            $request->validate([
                'no_sk_kepala_dinas' => 'required'
            ]);
        } else {
            $request->validate([
                'nip' => 'required|unique:pegawai|digits:18', //(unique)
                'tmt_pns' => 'required',
                'tmt_cpns' => 'required',
            ]);
        }

        Pegawai::create($request->toArray());
        return redirect()->route('pegawai.index')->with('success', 'Berhasil menambah data pegawai');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['pegawai'] = Pegawai::find($id);
        return view("pegawai.form", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required', //'Laki - laki', 'Perempuan',
            'alamat' => 'required',
            'no_telp' => 'required',
            'email' => 'required',
            'nik' => 'required|unique:pegawai,id,'.$id,
            'jenis_pegawai' => 'required',
        ]);

        if($request->jenis_pegawai == 2) {
            $request->validate([
                'no_sk_kepala_dinas' => 'required'
            ]);
        } else {
            $request->validate([
                'nip' => 'required|digits:18|unique:pegawai,id,'.$id, //(unique)
                'tmt_pns' => 'required',
                'tmt_cpns' => 'required',
            ]);
        }

        Pegawai::find($id)->update($request->toArray());
        return redirect()->route('pegawai.index')->with('success', 'Berhasil mengubah pegawai');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pegawai = Pegawai::find($id);
        $golongan = Golongan::where('pegawai_id', $id)->first();
        if($golongan != null) {
            $golongan->delete();
        }
        $jabatan_pegawai = JabatanPegawai::where('pegawai_id', $id)->delete();
        $pegawai->delete();
        return redirect()->route('pegawai.index')->with('success', 'Berhasil menghapus unit organisasi');
    }

    public function eksePegawai()
    {

        if(Auth::user()->level == 'Kepala Sub-bagian') {
            $jabatan_pegawai = JabatanPegawai::selectRaw('unit_organisasi_id, count(pegawai_id) as jumlah_sekarang')->where('jabatan_sekarang', 'true')->groupBy('unit_organisasi_id')->get();
            $data['jabatan_pegawai'] = $jabatan_pegawai;
            return view('pegawai.ekse_pegawai', $data);
        } else {
            return "Unauthorized";
        }
    }
}

resources/views/pegawai/ekse_pegawai.blade.php
@extends('layouts.app')

@section('title', 'Info Unit Organisasi')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Info Unit Organisasi</h4>
            </div>
            <div class="card-body">

                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Unit Organisasi / Bidang</th>
                            <th>Kapasitas</th>
                            <th>Jumlah Skrg</th>
                            <th>Status</th>

                        </tr>
                    </thead>
                    <tbody>
                        @forelse($jabatan_pegawai as $row)
                            @if($row->unitOrganisasi->nama_unit_organisasi == 'Pensiun')
                                @continue
                            @endif
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->unitOrganisasi->nama_unit_organisasi }}</td>
                                <td>{{ $row->unitOrganisasi->kapasitas }}</td>
                                <td>{{ $row->jumlah_sekarang }}</td>
                                <td>
                                    @if($row->unitOrganisasi->kapasitas > $row->jumlah_sekarang)
                                        <span class="badge badge-danger">Kekurangan</span>
                                    @elseif($row->unitOrganisasi->kapasitas == $row->jumlah_sekarang)
                                        <span class="badge badge-success">Jumlah sesuai</span>
                                    @else
                                        <span class="badge badge-warning">Kelebihan</span>
                                    @endif

                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="8">Belum ada data</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection

@push('scripts')

<script>
    $('.pegawai-sidebar').removeClass('active');
</script>

@endpush

resources/views/pegawai/form.blade.php
@extends('layouts.app')

@section('title', 'Form Pegawai')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Pegawai</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($pegawai->id)) ? route('pegawai.store') : route('pegawai.update', $pegawai->id) }}" method="post">
                    @csrf
                    @isset($pegawai->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label>Jenis Pegawai</label>
                                <select name="jenis_pegawai" class="form-control jenis-pegawai" id="jenis-pegawai">
                                    <option value="" class="text-dark"> - Pilih Jenis Pegawai - </option>
                                    <option class="text-dark" value="1" {{ old('jenis_pegawai', $pegawai->jenis_pegawai) == 1 ? 'selected' : '' }}>PNS</option>
                                    <option class="text-dark" value="2" {{ old('jenis_pegawai', $pegawai->jenis_pegawai) == 2 ? 'selected' : '' }}>Non-PNS / Kontrak / Lainnya</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="block-default">
                        <div class="form-group">
                            <label>Nama Pegawai</label>
                            <input type="text" placeholder="Nama pegawai" class="form-control" name="nama" value="{{ old('nama', $pegawai->nama) }}">
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Gelar Depan</label>
                                    <input type="text" placeholder="Masukan Gelar Depan" class="form-control" name="gelar_depan" value="{{ old('gelar_depan', $pegawai->gelar_depan) }}">
                                </div>
                                <div class="col-md-6">
                                    <label>Gelar Belakang</label>
                                    <input type="text" placeholder="Masukan Gelar Belakang" class="form-control" name="gelar_belakang" value="{{ old('gelar_belakang', $pegawai->gelar_belakang) }}">
                                </div>
                            </div>
                        </div>
                        <div class="block-default">
                            <div class="form-group">
                                <label>NIK (KTP)</label>
                                <input type="text" placeholder="Masukan NIK" class="form-control" name="nik" value="{{ old('nik', $pegawai->nik) }}">
                            </div>
                        </div>
                        <div class="block-pns" style="display: none">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <label for="">NIP</label>
                                        <input type="text" name="nip" placeholder="Masukan NIP"  class="form-control" value="{{ old('nip', $pegawai->nip) }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="block-non-pns" style="display: none">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>No. Urut Umum</label>
                                        <input type="text" name="no_urut_umum" placeholder="Masukan no urut umum" class="form-control" value="{{ old('no_urut_umum', $pegawai->no_urut_umum) }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Tempat Lahir</label>
                                    <input type="text" placeholder="Masukan Tempat Lahir" class="form-control" name="tempat_lahir" value="{{ old('tempat_lahir', $pegawai->tempat_lahir) }}">
                                </div>
                                <div class="col-md-6">
                                    <label>Tanggal Lahir</label>
                                    <input type="text" placeholder="Masukan Tanggal Lahir" class="form-control datepicker" name="tanggal_lahir" value="{{ old('tanggal_lahir', $pegawai->tanggal_lahir) }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <label>Jenis Kelamin</label>
                                    <select name="jenis_kelamin" class="form-control">
                                        <option value="" class="text-dark"> - Pilih Jenis Kelamin - </option>
                                        <option class="text-dark" value="Laki - laki" {{ old('jenis_kelamin', $pegawai->jenis_kelamin) == 'Laki - laki' ? 'selected' : '' }}>Laki - laki</option>
                                        <option class="text-dark" value="Perempuan" {{ old('jenis_kelamin', $pegawai->jenis_kelamin) == 'Perempuan' ? 'selected' : '' }}>Perempuan</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>No. Telp</label>
                                    <input type="text" placeholder="Masukan No. Telp" class="form-control" name="no_telp" value="{{ old('no_telp', $pegawai->no_telp) }}">
                                </div>
                                <div class="col-md-6">
                                    <label>Email</label>
                                    <input type="text" placeholder="Masukan Email" class="form-control" name="email" value="{{ old('email', $pegawai->email) }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Alamat</label>
                            <textarea name="alamat" class="form-control" placeholder="Masukan Alamat">{{ old('alamat', $pegawai->alamat) }}</textarea>
                        </div>
                    </div>
                    <div class="block-pns" style="display: none">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <label>SK. PNS</label>
                                    <input type="text" name="sk_pns" class="form-control" value="{{ old('sk_pns', $pegawai->sk_pns) }}">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="block-pns" style="display: none">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="">Terhitung Mulai Tanggal PNS</label>
                                    <input type="text" name="tmt_pns" class="form-control datepicker2" value="{{ old('tmt_pns', $pegawai->tmt_pns) }}">
                                </div>
                                <div class="col-md-6">
                                    <label for="">Terhitung Mulai Tanggal CPNS</label>
                                    <input type="text" name="tmt_cpns" class="form-control datepicker2" value="{{ old('tmt_cpns', $pegawai->tmt_cpns) }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="block-non-pns" style="display: none">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <label>No. SK. Kepala Dinas</label>
                                    <input type="text" name="no_sk_kepala_dinas" class="form-control" value="{{ old('no_sk_kepala_dinas', $pegawai->no_sk_kepala_dinas) }}">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

<script>
    $('.pegawai-sidebar').addClass('active');
    //console.log($('.jenis-pegawai').val());
    if($('.jenis-pegawai').val() == 1) {
        $('.block-pns').show();
        $('.block-non-pns').hide();
        $('.block-default').show();
    }
    if($('.jenis-pegawai').val() == 2) {
        $('.block-pns').hide();
        $('.block-non-pns').show();
        $('.block-default').show();
    }
    $('.jenis-pegawai').change(function(){

        if($(this).val().length == 0){
            $('.block-pns').hide();
            $('.block-default').hide();
            $('.block-non-pns').hide();
        }
        if($(this).val() == 1){
            $('.block-pns').show();
            $('.block-default').show();
            $('.block-non-pns').hide();
        }
        if($(this).val() == 2){
            $('.block-pns').hide();
            $('.block-default').show();
            $('.block-non-pns').show();
        }
    });
</script>

@endpush

resources/views/pegawai/index.blade.php
@extends('layouts.app')

@section('title', 'Pegawai')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Pegawai</h4>
            </div>
            <div class="card-body">
                @if(Auth::user()->level != 'Kepala Sub-bagian')
                    <a href="{{ route('pegawai.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah</a>
                @endif
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Pegawai</th>
                            <th>NIK</th>
                            <th>NIP / No. Urut Umum</th>
                            <th>TTL</th>
                            <th>JK</th>
                            <th>No. Telp</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($pegawai as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->namaGelar() }}</td>
                                <td>{{ $row->nik }}</td>
                                <td>{{ $row->jenis_pegawai == 1 ? $row->nik : $row->no_urut_umum }}</td>
                                <td>{{ $row->tempat_lahir . ', '. $row->tanggal_lahir }}</td>
                                <td>{{ $row->jenis_kelamin }}</td>
                                <td>{{ $row->no_telp }}</td>
                                <td>
                                    <span class="badge badge-{{ $row->jenis_pegawai == 1 ? 'info' : 'warning' }}">
                                        {{ $row->jenisPegawai() }}
                                    </span>
                                </td>
                                <td>
                                    <form action="{{ route('pegawai.destroy', $row->id) }}" method="post">
                                        <ul class="d-flex action-button">
                                            <li><a href="{{ route('print.pegawai', $row->id) }}" class="text-info" title="Print Data Pegawai" target="_blank"><i class="fa fa-print"></i></a></li>
                                            @if(Auth::user()->level != 'Kepala Sub-bagian')
                                                <li><a href="{{ route('pegawai.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                                @csrf
                                                @method('delete')
                                                <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                            @endif
                                        </ul>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="8">Belum ada data</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection

@push('scripts')

<script>
    $('.pegawai-sidebar').addClass('active');
</script>

@endpush